Repository jstnceronio/gibb-marketplace, pull requests merged in 2022-06, with the labels that each got.

#77 Don't display placeholders
  marketplace/src/app/pages/dashboard/dashboard.component.html
Labels: bug

#76 sort based on uid and not wrong username
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/shared/post/post.component.ts
  marketplace/src/app/shared/post/post.model.ts
Labels: bug

#88 Make the comments great again
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.html
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.scss
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.html
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.scss
  marketplace/src/app/shared/post/post.component.html
Labels: enhancement

#87 85 make tribes great again
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/pages/post/create/create.component.html
  marketplace/src/app/pages/post/create/create.component.ts
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.html
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.html
  marketplace/src/app/shared/post/post.component.html
  marketplace/src/app/shared/post/post.component.scss
  marketplace/src/app/shared/post/post.component.ts
Labels: enhancement

#91 Added firebase config
  marketplace/.firebaserc
  marketplace/.github/workflows/main.yml
  marketplace/firebase.json
  marketplace/firestore.indexes.json
  marketplace/firestore.rules
  marketplace/src/404.html
Labels: enhancement

#92 48 firebase deployment
  marketplace/.gitignore
  marketplace/firebase.json
  marketplace/package.json
  marketplace/workflows/main.yml
Labels: enhancement

#93 bruh
  .github/workflows/main.yml
Labels: enhancement

#96 Fixed all translations to german
  marketplace/src/app/pages/post/comment/comment-form.component.html
  marketplace/src/app/pages/profile/profile.component.html
  marketplace/src/app/pages/register/register.component.html
  marketplace/src/app/shared/post/post.component.html
  marketplace/src/app/shared/side-bar/side-bar.component.html
Labels: enhancement, bonus
