Repository jstnceronio/gibb-marketplace, pull requests merged in 2022-05, with the labels that each got.

#14 Login view
  marketplace/package-lock.json
  marketplace/src/app/app.component.html
  marketplace/src/app/pages/login/login.component.html
  marketplace/src/app/pages/login/login.component.scss
  marketplace/src/styles.scss
  marketplace/tailwind.config.js
Labels: enhancement

#21 Finish registration view
  marketplace/src/app/pages/register/register.component.html
  marketplace/src/app/pages/register/register.component.scss
Labels: enhancement

#23 Form validation on registration view
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/pages/register/register.component.html
  marketplace/src/app/pages/register/register.component.ts
Labels: enhancement

#29 Dashboard view
  marketplace/package-lock.json
  marketplace/package.json
  marketplace/src/app/app.component.html
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.scss
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/shared/post/post.component.html
  marketplace/src/app/shared/post/post.component.scss
  marketplace/src/app/shared/post/post.component.spec.ts
  marketplace/src/app/shared/post/post.component.ts
Labels: enhancement

#36 Add creation component for posts (template)
  marketplace/src/app/app-routing/app-routing.module.ts
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.scss
  marketplace/src/app/pages/post/create/create.component.html
  marketplace/src/app/pages/post/create/create.component.scss
  marketplace/src/app/pages/post/create/create.component.spec.ts
  marketplace/src/app/pages/post/create/create.component.ts
Labels: enhancement

#37 Profile template
  marketplace/src/app/app-routing/app-routing.module.ts
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/profile/profile.component.html
  marketplace/src/app/pages/profile/profile.component.scss
  marketplace/src/app/pages/profile/profile.component.spec.ts
  marketplace/src/app/pages/profile/profile.component.ts
Labels: enhancement

#41 Button behavior in registration view
  marketplace/package-lock.json
  marketplace/src/app/pages/register/register.component.html
  marketplace/src/app/pages/register/register.component.ts
  marketplace/src/app/services/auth.service.ts
Labels: enhancement

#46 Profile view functionality
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/profile/profile.component.html
  marketplace/src/app/pages/profile/profile.component.scss
  marketplace/src/app/pages/profile/profile.component.ts
  marketplace/src/app/pages/register/register.component.ts
  marketplace/src/app/services/auth.service.ts
  marketplace/src/app/services/user.model.ts
  marketplace/src/assets/img/placeholder.jpg
  marketplace/tsconfig.json
Labels: enhancement

#50 Added navbar
  marketplace/src/app/app.component.html
  marketplace/src/app/app.component.scss
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/login/login.component.html
  marketplace/src/app/pages/login/login.component.scss
  marketplace/src/app/pages/login/login.component.ts
  marketplace/src/app/shared/side-bar/side-bar.component.html
  marketplace/src/app/shared/side-bar/side-bar.component.scss
  marketplace/src/app/shared/side-bar/side-bar.component.spec.ts
  marketplace/src/app/shared/side-bar/side-bar.component.ts
Labels: enhancement

#51 Like and comment
  marketplace/package-lock.json
  marketplace/package.json
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/pages/post/comment/comment-form.component.html
  marketplace/src/app/pages/post/comment/comment-form.component.scss
  marketplace/src/app/pages/post/comment/comment-form.component.spec.ts
  marketplace/src/app/pages/post/comment/comment-form.component.ts
  marketplace/src/app/pages/post/comment/comment.component.html
  marketplace/src/app/pages/post/comment/comment.component.scss
  marketplace/src/app/pages/post/comment/comment.component.spec.ts
  marketplace/src/app/pages/post/comment/comment.component.ts
  marketplace/src/app/pages/post/comment/comment.model.ts
  marketplace/src/app/pages/register/register.component.ts
  marketplace/src/app/services/data.service.ts
  marketplace/src/app/shared/post/post.component.html
  marketplace/src/app/shared/post/post.component.ts
  marketplace/src/app/shared/post/post.model.ts
Labels: enhancement

#55 Sidebar refinement
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/shared/side-bar/side-bar.component.html
  marketplace/src/app/shared/side-bar/side-bar.component.scss
  marketplace/src/app/shared/side-bar/side-bar.component.ts
Labels: enhancement

#54 Filter is working on dashboard
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/services/data.service.ts
Labels: bug, enhancement

#58 username is displayed underneath post title
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/post/create/create.component.ts
  marketplace/src/app/services/data.service.ts
  marketplace/src/app/shared/post/post.component.html
  marketplace/src/app/shared/post/post.component.ts
  marketplace/src/app/shared/post/post.model.ts
Labels: enhancement

#60 57 add post single view
  marketplace/package-lock.json
  marketplace/src/app/app-routing/app-routing.module.ts
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/dashboard/dashboard.component.html
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.html
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.scss
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.spec.ts
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.ts
  marketplace/src/app/services/data.service.ts
  marketplace/src/app/shared/post/post.component.html
  marketplace/tsconfig.json
Labels: enhancement

#70 Display avatar in profile and dashboard view
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/pages/login/login.component.html
  marketplace/src/app/pages/login/login.component.ts
  marketplace/src/app/pages/profile/profile.component.html
  marketplace/src/app/pages/profile/profile.component.ts
  marketplace/src/app/pages/register/register.component.ts
  marketplace/src/app/services/auth.service.ts
  marketplace/src/app/services/data.service.ts
  marketplace/src/app/shared/post/post.component.html
  marketplace/src/app/shared/post/post.component.ts
  marketplace/src/app/shared/side-bar/side-bar.component.html
Labels: enhancement

#65 61 add comment logic in post single view
  marketplace/src/app/pages/dashboard/dashboard.component.ts
  marketplace/src/app/pages/post/create/create.component.ts
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.html
  marketplace/src/app/pages/post/single-view/post-view/post-view.component.ts
Labels: enhancement

#67 63 bug editing profile making unlimited requests
  marketplace/src/app/pages/profile/profile.component.html
  marketplace/src/app/pages/profile/profile.component.ts
  marketplace/src/app/services/auth.service.ts
Labels: bug

#69 68 my posts view
  marketplace/src/app/app-routing/app-routing.module.ts
  marketplace/src/app/app.module.ts
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.html
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.scss
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.spec.ts
  marketplace/src/app/pages/post/profile-post-view/profile-post-view.component.ts
  marketplace/src/app/services/auth.service.ts
  marketplace/src/app/shared/side-bar/side-bar.component.html
Labels: enhancement

#71 change validation on registration
  marketplace/src/app/pages/register/register.component.html
  marketplace/src/app/pages/register/register.component.scss
  marketplace/src/app/pages/register/register.component.ts
Labels: enhancement
